stages:
  - build
  - test
  - deploy

variables:
  HELLO_STRING: 'Hello CI/CD!'

build-job:
  stage: build
  script:
    - echo ${HELLO_STRING}

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 5 seconds."
    - sleep 5
    - echo "Code coverage is 666%"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Server in fire! Your commit has broken prod..."
