stages:
  - build

variables:
  GITLAB_ALLOW_PRIVILEGED: 'true'

include:
  - local: 'pipelines/account.yml'
  - local: 'pipelines/aggregator.yml'
  - local: 'pipelines/friend.yml'
  - local: 'pipelines/geo.yml'
  - local: 'pipelines/message.yml'
  - local: 'pipelines/notification.yml'
  - local: 'pipelines/post.yml'
  - local: 'pipelines/storage.yml'
