version: '3'
services:
  pgsql:
    image: 'postgres:14'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    ports:
      - '${SN_DB_PORT}:5432'
    environment:
      PGPASSWORD: ${SN_DB_PASSWORD}
      POSTGRES_DB: ${SN_DB_NAME}
      POSTGRES_USER: ${SN_DB_USER}
      POSTGRES_PASSWORD: ${SN_DB_PASSWORD}
    networks:
      - server

#  aggregator:
#    image: 'intouchgroup/aggregator'
#    ports:
#      - '${SN_AGGREGATOR_PORT}:${SN_AGGREGATOR_PORT}'
#    environment:
#      SN_AGGREGATOR_PORT: ${SN_AGGREGATOR_PORT}
#      SN_NOTIFICATIONS_PORT: ${SN_NOTIFICATIONS_PORT}
#      SN_NOTIFICATIONS_HOST: notifications
#    depends_on:
#      - pgsql
#      - notifications
#    networks:
#      - server
#
#  notifications:
#    image: 'intouchgroup/notification-serv'
#    ports:
#      - '${SN_NOTIFICATIONS_PORT}:${SN_NOTIFICATIONS_PORT}'
#    networks:
#      - server
#    depends_on:
#      - pgsql
#    environment:
#      SN_DB_PASSWORD: ${SN_DB_PASSWORD}
#      SN_DB_NAME: ${SN_DB_NAME}
#      SN_DB_USER: ${SN_DB_USER}
#      SN_DB_HOST: pgsql
#      SN_DB_PORT: ${SN_DB_PORT}
#      SN_NOTIFICATIONS_PORT: ${SN_NOTIFICATIONS_PORT}
#      SN_NOTIFICATIONS_HOST: notifications

#  front:
#    image: 'typuctroot/front-localhost'
#    ports:
#      - '80:80'
#    networks:
#      - server

networks:
  server:
    driver: bridge
volumes:
  pgsql:
    driver: local
