apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-k8s-app
  labels:
    project: k8s-test-spring-project
spec:
  replicas: 3
  selector:
    matchLabels:
      project: k8s-test-spring-project
  template:
    metadata:
      labels:
        project: k8s-test-spring-project #Service will look for those PODs
    spec:
      containers:
        - name:  test-spring-container
          image: dkapriz/test-spring-app:0.0.2 #link on docker image
          ports:
          - containerPort: 8080 #Port on POD

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-service
  labels:
    project: k8s-test-spring-project
spec:
  selector:
    project: k8s-test-spring-project #Selecting PODs with those Labels
  ports:
    - name: app-listner
      protocol: TCP
      port: 8000
      targetPort: 8080
  type: NodePort