apiVersion: v1
kind: Pod
metadata:
  name: kuber-test-pod
  labels: 
    environment: dev 
    app: http-server
spec:
  containers:
  - name: test-spring-container
    image: dkapriz/test-spring-app:0.0.2 #link on docker image
    ports:
    - containerPort: 8080