spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/socialnetwork
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/dbchangelog-master.xml
