server.port: 8085

spring.datasource.url: jdbc:postgresql://localhost:5432/social-network
spring.datasource.username: d.kapriz
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.hibernate.ddl-auto: none
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: true

spring.liquibase.enabled: false
spring.liquibase.change-log: classpath:dbchangelog-master.xml
