spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false


  liquibase:
    enabled: true
    change-log: classpath:/dbchangelog-master.xml


