spring:
  kafka:
    notification-serv: ${SN_NOTIFICATION_SERV}
    bootstrap-servers: ${SN_KAFKA_HOST}:${SN_KAFKA_PORT}
    consumer:
      group-id: aggregator_serv
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              package: "*"

server:
  port: 8080
  api:
    protocol: ${SN_PROTOCOL}
    prefix: /api/v1
    account: ${server.api.protocol}${SN_ACCOUNT_HOST}:${SN_ACCOUNT_PORT}${server.api.prefix}/account/me

websocket:
  endpoint: ${SN_WEBSOCKET_HTTP_ENDPOINT}
