server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/social_network?createDatabaseIfNotExist=true
    username: postgres
    password: 654321
    driver-class-name: org.postgresql.Driver