server:
  port: 8050

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:8090/socialnetwork
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: false

  sql:
    init:
      data-locations:
        classpath:/sql-scripts/post_tags.sql, classpath:/sql-scripts/post_type.sql,
        classpath:/sql-scripts/posts.sql, classpath:/sql-scripts/post2tags.sql
      mode: never

  liquibase:
    enabled: true
    change-log: classpath:/dbchangelog-master.xml
